---
type: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --remote
- name: hugo-builder
  image: jojomi/hugo:0.55.0
  commands:
  - hugo
...
