---
type: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: docker:git
  volumes:
  - name: cache
    path: ./themes/even
  commands:
  - git submodule init
  - git submodule update --recursive --remote
  - ls ./themes/even

- name: hugo-builder
  image: jojomi/hugo:0.55.0
  commands:
  - hugo

- name: release
  image: plugins/docker
  settings:
    debug: true
    password:
      from_secret: docker_password
    repo: qianlongzt/blog
    tags: latest
    username: qianlongzt
  when:
    branch:
    - master
    event:
    - push

volumes:
- name: cache
  host:
    path: /root/blog/git
...
