---
type: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule init
  - git submodule update --recursive --remote
  - ls ./themes/even

- name: hugo-builder
  image: jojomi/hugo:0.55.0
  commands:
  - hugo

- name: release
  image: docker
  settings:
    password:
      from_secret: docker_password
    repo: qianlongzt/blog
    tag: latest
    username: qianlongzt
    commands:
    - docker login -u ${DRONE_USERNAME} -p ${DRONE_PASSWORD}
    - docker build -t ${DRONE_REPO}:${DRONE_TAG} .
    - docker push ${DRONE_REPO}:${DRONE_TAG}
  when:
    event:
    - push
...
