---
type: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule init
  - git submodule update --recursive --remote
  - ls ./themes/even

- name: hugo-builder
  image: jojomi/hugo:0.55.0
  commands:
  - hugo

- name: release
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    repo: qianlongzt/blog
    tags: latest
    username: qianlongzt
    debug: true

...
