---
type: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule init
  - git submodule update --recursive --remote
  - ls ./themes/even

- name: hugo-builder
  image: jojomi/hugo:0.55.0
  commands:
  - hugo

- name: release
  image: docker
  commands:
  - "docker login -u $PLUGIN_USERNAME -p $PLUGIN_PASSWORD"
  - "docker build -t $PLUGIN_REPO:$PLUGIN_TAG ."
  - "docker push $PLUGIN_REPO:$PLUGIN_TAG"
  settings:
    password:
      from_secret: docker_password
    repo: qianlongzt/blog
    tag: latest
    username: qianlongzt
  when:
    branch:
    - master

...
